package com.awake.util;

import com.awake.util.base.StringUtils;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Arrays;

/**
 * @version : 1.0
 * @ClassName: ExceptionUtils
 * @Description: TODO
 * @Auther: awake
 * @Date: 2023/3/10 16:44
 **/
public class ExceptionUtils {

    /**
     * 获取异常全部信息，格式是：
     * <p>
     * 类名称: 异常信息
     * 异常堆栈
     * </p>
     *
     * @param throwable the throwable to get a message for, null returns empty string
     * @return 异常的信息
     */
    public static String getMessage(final Throwable throwable) {
        if (throwable == null) {
            return StringUtils.EMPTY;
        }
        final String className = throwable.getClass().getName();
        return className + ": " + throwable.getMessage() + FileUtils.LS
                + getStackTrace(throwable);
    }


    /**
     * <p>Gets the stack trace from a Throwable as a String.</p>
     * <p>The result of this method vary by JDK version as this method uses {@link Throwable#printStackTrace(java.io.PrintWriter)}.
     *
     * @param throwable the <code>Throwable</code> to be examined
     * @return the stack trace as generated by the exception's
     */
    public static String getStackTrace(final Throwable throwable) {
        final StringWriter sw = new StringWriter();
        final PrintWriter pw = new PrintWriter(sw, true);
        throwable.printStackTrace(pw);
        return sw.getBuffer().toString();
    }

    public static String getCurrentStackTrace() {
        StringBuilder builder = new StringBuilder();
        StackTraceElement[] stackTraces = Thread.currentThread().getStackTrace();
        Arrays.stream(stackTraces).forEach(it -> builder.append(it.toString()).append(FileUtils.LS));
        return builder.toString();
    }
}
